### ISSUE TITLE
'response' werkt niet in python example - 'withdraw' als response wel

### ISSUE THREAD

**Issue by mskelo** [luukk/noob#11]
Zie titel. Ik heb de code van de python example aangepast om originCountry en originBank ook mee te sturen, omdat anders responses niet aan zouden kunnen komen. Bij testen werkt de routing via de NOOB perfect wanneer 'withdraw' requests worden verstuurd, alleen komen de 'response' packets nooit aan of worden ze nooit verstuurd. Als ik de 'response' als 'withdraw' terugstuur werkt het wel. 

```
import socketio

io = socketio.Client()

io.connect('http://145.24.222.206:8085')

@io.event
def response(data):
    print(data)

@io.event
def withdraw(data):
    # Handle your withdraw request and respond
    print(data)
    response = {
        'header': { 
            'originCountry': 'TE1',
            'originBank': 'INGB',
            'receiveCountry': data['header']['originCountry'],
            'receiveBank': data['header']['originBank'],
            'action': 'withdraw'
        },
        'body': {
            'code': 200,
            'message': 'Success'
        }
    }
    io.emit('response', response)
    #io.emit('withdraw', response) werkt dus wel

withdrawBody = {
    'header': { 
	'originCountry': 'TE1',
	'originBank': 'INGB',
        'receiveCountry': 'TE0',
        'receiveBank': 'INGB'
    },
    'body': {
        'pin': '1234',
        'account': '123456',
        'acmount': 123.45
    }
}

io.emit('withdraw', withdrawBody)

```

**Comment by Nick-v-L** [comment]
In de code stond een typefout reponse ipv response waardoor het niet goed werd doorgestuurd. Voor de rest de withdraw code geupdate met originCountry. Zal versie 1.0 opnieuw publiceren.

**Comment by mskelo** [comment]
Merci. Hij werkt perfect nu. NOOB (en testland TE0) draaien op 145.24.222.206:8085. Ik heb n.a.v. deze issue de handleiding aangepast en gelijk wat leesbaarder gemaakt.
